set(TARGET_NAME datalol)

add_library(${TARGET_NAME} STATIC
  # Please keep this list sorted
  memory.cpp
  query.cpp
  syntax.cpp
  trace.cpp
)

install( TARGETS ${TARGET_NAME}
    ARCHIVE DESTINATION lib PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE
    LIBRARY DESTINATION bin PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE
)

install(DIRECTORY "${CMAKE_SOURCE_DIR}/include/"
    DESTINATION include
    PATTERN "bits" EXCLUDE
)
